repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-toml
  - id: check-yaml
  - id: check-xml
  - id: check-json
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: trailing-whitespace
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.7
  hooks:
  - id: ruff
- repo: local
  hooks:
  - id: mypy
    name: mypy
    language: system
    entry: sh -c 'git ls-files -z "*.py" | xargs -0 uv run mypy'
    require_serial: true
    pass_filenames: false
    always_run: true
    verbose: true
- repo: local
  hooks:
  - id: pytest
    name: pytest
    language: system
    entry: uv run pytest -n auto
    require_serial: true
    pass_filenames: false
    always_run: true
    verbose: true
    stages: [pre-push]
