name: test-production

on:
  workflow_run:
    workflows: [test]
    branches: [main]
    types: [completed]

env:
  FORCE_COLOR: 3

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v5
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "requirements**.txt"
    - run: uv venv
    - run: uv pip install -r requirements-dev.txt
    - run: uv run pytest tests/test_selenium.py --production
