name: test-production

on:
  workflow_run:
    workflows: [test]
    branches: [main]
    types: [completed]

env:
  FORCE_COLOR: 3

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v5
    - run: pip install --upgrade pipenv wheel
    - run: pipenv install --dev
    - run: pipenv run pytest tests/test_selenium.py --production
